### ISSUE TITLE
Full download taiga corpus

### ISSUE THREAD

**Issue by sshaplygin** [TatianaShavrina/taiga_site#4]
Hi, Tatina.

Sorry, but can you publish your taiga corpus into torrent?

Because full corpus is so large and i can't download them 😢

**Comment by TatianaShavrina** [comment]
That's a cool idea, thank you!

To resolve your issue now - maybe I could help you with a smaller subcorpus for your research needs?

The download link also works with wget

**Comment by sshaplygin** [comment]
@TatianaShavrina thanks for answer!
I downloaded full subcorpus with my little linux server 💃 
Thanks for your work!
